# Generated by Django 2.1 on 2018-08-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_nums',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
