# Generated by Django 2.1 on 2018-08-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_comment_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_nums',
        ),
    ]
